### ISSUE TITLE
function.py

### ISSUE THREAD

**Issue by cemilzalluhoglu** [HHTseng/video-classification#2]
I can't find the function.py. I think it is a necessary file for UCF101_ResNetCRNN.py

UCF101_ResNetCRNN.py

> from functions import *

> cnn_encoder = ResCNNEncoder(fc_hidden1=CNN_fc_hidden1, fc_hidden2=CNN_fc_hidden2, drop_p=dropout_p, CNN_embed_dim=CNN_embed_dim).to(device)

> rnn_decoder = DecoderRNN(CNN_embed_dim=CNN_embed_dim, h_RNN_layers=RNN_hidden_layers, h_RNN=RNN_hidden_nodes,                        h_FC_dim=RNN_FC_dim, drop_p=dropout_p, num_classes=k).to(device)

**Comment by HHTseng** [comment]
Yes, the functions.py is necessary as you should be able to find it in every folder, eg.
<img width="999" alt="resnetCRNN" src="https://user-images.githubusercontent.com/24979292/57182646-78493680-6e6f-11e9-8c1b-882405313cd2.png">
please let me know if you still cannot see it
