### ISSUE TITLE
Error extracting Part 3 of the dataset

### ISSUE THREAD

**Issue by ghost** [HHTseng/video-classification#4]
Hello!

I have a very weird problem. I have successfully downloaded and extracted Part 1 and Part 2 of the UCF101 dataset. However, I get an error when trying to unzip Part 3 of the dataset.
Could you please help me solve this issue?

Thank you in advance. 

I receive this message: 
Error extracting 'ucf101_jpegs_256.zip.003' 
Invalid format

**Comment by HHTseng** [comment]
Hello, thanks for the practical and nice question! 
I seemed to encounter that before, but didn't really have a brilliant idea but to download it again or change a machine, and it can be passed somehow. My thought is that there are so many snippet files so the zip files could easily go wrong. 
Sorry that my reply may not be very helpful, but the bottom line is that those files do have a chance to work correctly as my friend and I have verified that.
I also looked into the [issues of feichtenhofer/twostreamfusion](https://github.com/feichtenhofer/twostreamfusion/issues), didn't find this issue addressed. Please let me know if you can solve this somehow, thanks!

**Comment by mampferd** [comment]
Just the .001 file needs to be unzipped. This will concatenate the three elements .001, .002 and .003 to jpegs again

**Comment by immkapoor** [comment]
Hi, I am not able to unzip .001 file with error stating it to be null though it's 9 GB file. Can anyone help ?
